permalink:           pretty

# Setup
title:               'kmeans PyTorch'
#tagline:             'A Jekyll theme'
url:                 https://subhadarship.github.io/kmeans_pytorch/
baseurl:             '/kmeans_pytorch'

# About/contact
author:
  name:              Subhadarshi Panda
  url:               https://subhadarship.github.io
github:
  repo:              https://github.com/subhadarship/kmeans_pytorch/

# Custom vars
version:             0.3

multilingual:        false
src:                 "."
default_theme:       "Rust"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true

# Chapter Configuration (up to a 2 level nested list)

chapters:
  - path: chapters/example/example.md
  - path: chapters/cpu_vs_gpu/cpu_vs_gpu.md
